export const TEXTS = {
  APP_TITLE: '基金股票助手',
  COMMON: {
    LOADING: '加载中...',
    FAILED_LOAD_DATA: '加载数据失败',
    UPDATED: '已更新',
    SORT: '排序',
    TOTAL_ASSET: '总资产 (¥)',
    DAILY_INCOME: '当日收益',
    DAILY_YIELD: '日涨跌幅',
    NAV: '净值',
    DAILY_EARN: '日收益',
    TOTAL_EARN: '总收益',
  },
  HOME: {
    MARKET_INDEX: '大盘指数',
    MY_FUNDS: '我的基金',
    SORT_COMMON: '默认',
    SORT_SECTOR: '板块',
    SORT_DAILY: '日涨跌',
    SORT_HOLD: '持仓',
  },
  FUND_DETAIL: {
    TITLE: '基金详情',
    NOT_FOUND: '未找到基金',
    FAILED_LOAD_DETAIL: '加载基金详情失败',
    HOLDINGS: '持仓详情',
    PRINCIPAL: '本金',
    HOLD_EARNING: '持有收益',
    BASIC_INFO: '基本信息',
    TYPE: '类型',
    STYLE: '风格',
    WORTH: '价值风格',
    RISK: '风险等级',
    RELATED_INDUSTRY: '关联板块',
  },
};
